name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile main program
      run: gcc main.c -o calculator
    - name: Compile and run tests
      run: |
        gcc test.c -o test
        ./test
